apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: web
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: web
    name: web
  spec:
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: web
    template:
      metadata:
        labels:
          deploymentconfig: web
      spec:
        containers:
        - image: web
          imagePullPolicy: Always
          name: web
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - web
        from:
          kind: ImageStreamTag
          name: web:test
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: web
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: web
    name: web
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: web
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: web
    name: web
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: web
      weight: 100
    wildcardPolicy: None

